// Find the Difference

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char,int> m;
        for(int i=0;i<s.length();i++)
        {
            if(m.find(s[i])==m.end())
            {
                m.insert({s[i],1});
            }
            else
            {
                m[s[i]]+=1;
            }
        }
        for(int i=0;i<t.length();i++)
        {
            if(m.find(t[i])==m.end() || m[t[i]]==0)
                return t[i];
            else
                m[t[i]]--;
        }
        return t[0];
    }
};